package dev.jlm.leadshunter.lead;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public record LeadResponse(
    Long id,
    String googlePlaceId,
    String nome,
    String cnpj,
    String razaoSocial,
    CategoriaNegocio categoria,
    String enderecoFormatado,
    String website,
    String telefone,
    String telefoneNormalizado,
    String whatsappUrl,
    BigDecimal latitude,
    BigDecimal longitude,
    String municipioCodigoIbge,
    String municipioNome,
    String uf,
    BigDecimal idhm,
    Short idhmReferencia,
    BigDecimal ratingGoogle,
    Integer totalReviews,
    Integer score,
    Temperatura temperatura,
    StatusFunil status,
    String observacoes,
    LocalDateTime ultimoContatoEm,
    LocalDateTime criadoEm,
    LocalDateTime atualizadoEm
) {

    public LeadResponse(
        Long id,
        String googlePlaceId,
        String nome,
        String cnpj,
        String razaoSocial,
        CategoriaNegocio categoria,
        String enderecoFormatado,
        String telefone,
        String telefoneNormalizado,
        String whatsappUrl,
        BigDecimal latitude,
        BigDecimal longitude,
        String municipioCodigoIbge,
        String municipioNome,
        String uf,
        BigDecimal idhm,
        Short idhmReferencia,
        BigDecimal ratingGoogle,
        Integer totalReviews,
        Integer score,
        Temperatura temperatura,
        StatusFunil status,
        String observacoes,
        LocalDateTime ultimoContatoEm,
        LocalDateTime criadoEm,
        LocalDateTime atualizadoEm
    ) {
        this(
            id,
            googlePlaceId,
            nome,
            cnpj,
            razaoSocial,
            categoria,
            enderecoFormatado,
            null,
            telefone,
            telefoneNormalizado,
            whatsappUrl,
            latitude,
            longitude,
            municipioCodigoIbge,
            municipioNome,
            uf,
            idhm,
            idhmReferencia,
            ratingGoogle,
            totalReviews,
            score,
            temperatura,
            status,
            observacoes,
            ultimoContatoEm,
            criadoEm,
            atualizadoEm
        );
    }

    public static LeadResponse from(Lead lead, WhatsAppLinkGenerator whatsAppLinkGenerator) {
        return new LeadResponse(
            lead.getId(),
            lead.getGooglePlaceId(),
            lead.getNome(),
            lead.getCnpj(),
            lead.getRazaoSocial(),
            lead.getCategoria(),
            lead.getEnderecoFormatado(),
            lead.getWebsite(),
            lead.getTelefone(),
            lead.getTelefoneNormalizado(),
            whatsAppLinkGenerator.gerar(lead.getTelefoneNormalizado()),
            lead.getLatitude(),
            lead.getLongitude(),
            lead.getMunicipioCodigoIbge(),
            lead.getMunicipioNome(),
            lead.getUf(),
            lead.getIdhm(),
            lead.getIdhmReferencia(),
            lead.getRatingGoogle(),
            lead.getTotalReviews(),
            lead.getScore(),
            lead.getTemperatura(),
            lead.getStatus(),
            lead.getObservacoes(),
            lead.getUltimoContatoEm(),
            lead.getCriadoEm(),
            lead.getAtualizadoEm()
        );
    }
}
